### ISSUE TITLE
Add configuration file for GitHub Probot Settings App

### ISSUE THREAD

**Issue by hassankhan** [EndemolShineGroup/generator-nodejs-ts#19]
### What is the use case that should be solved?

We want to be able to use the [Probot Settings App][link-app]. We need to add a file to the `.github` folder as per the instructions.

[link-app]: https://github.com/probot/settings

### If there is additional config how would it look?

<details>
<summary>Public</summary>

```yaml
# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:

  # Either `true` to make the repository private, or `false` to make it public.
  private: false

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable projects for this repository, or `false` to disable them.
  # If projects are disabled for the organization, passing `true` will cause an API error.
  has_projects: false

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: true

  # Updates the default branch for this repository.
  default_branch: develop

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: false

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: false

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true

branches:
  - name: master
    # https://developer.github.com/v3/repos/branches/#update-branch-protection
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: [ @esg-bot, @hassankhan ]
          teams: []
      required_status_checks:
        strict: true
        contexts: [ codecov/project, continuous-integration/travis-ci ]
      enforce_admins: true
      restrictions:
        users: [ @esg-bot, @hassankhan ]
        teams: []
  - name: develop
    # https://developer.github.com/v3/repos/branches/#update-branch-protection
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: [ @esg-bot, @hassankhan ]
          teams: []
      required_status_checks:
        strict: true
        contexts: [ codecov/project, continuous-integration/travis-ci ]
      enforce_admins: true
      restrictions:
        users: [ @esg-bot, @hassankhan ]
        teams: []
```

</details>

<details>

<summary>Private</summary>

```yaml
# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:

  # Either `true` to make the repository private, or `false` to make it public.
  private: true

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: false

  # Either `true` to enable projects for this repository, or `false` to disable them.
  # If projects are disabled for the organization, passing `true` will cause an API error.
  has_projects: false

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: false

  # Updates the default branch for this repository.
  default_branch: develop

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: false

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: false

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true

branches:
  - name: master
    # https://developer.github.com/v3/repos/branches/#update-branch-protection
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: [ @esg-bot, @hassankhan ]
          teams: []
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      restrictions:
        users: [ @esg-bot, @hassankhan ]
        teams: []
  - name: develop
    # https://developer.github.com/v3/repos/branches/#update-branch-protection
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: [ @esg-bot, @hassankhan ]
          teams: []
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      restrictions:
        users: [ @esg-bot, @hassankhan ]
        teams: []
```

</details>

## Additional Data

***Version of `generator-nodejs-ts` you're using***: 1.3.2

***Node Version***: 8.11

***Operating System***: macOS 10.13
